name: CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest, windows-latest  ]
        smalltalk: [ Pharo64-14 ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }}
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Setup Smalltalk CI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}

      - name: Run tests for current repository
        run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15

      # 👇 Added step: clone the external repo and test it too
      - name: Clone HeuristicCompletion-Analyser repository
        run: |
          git clone https://github.com/omarabedelkader/HeuristicCompletion-Analyser.git
          cd HeuristicCompletion-Analyser
          ls -la

      - name: Run tests in HeuristicCompletion-Analyser
        run: |
          cd HeuristicCompletion-Analyser
          smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15
